// Main module exports for programmatic use
export { loadConfig, resolvedConfig, saveConfig, getConfigPath } from './config/config.js'
export type { ClaraConfig, AgentConfigEntry, BindingConfigEntry } from './config/types.js'
export { createDefaultDeps } from './cli/deps.js'
export type { AppDeps } from './cli/deps.js'
export { startGateway } from './gateway/server.js'
export { handleAgentCall } from './gateway/call.js'
export { AuthService } from './gateway/auth.js'
export { Database } from './infra/db.js'
export { createLogger, initFileLogging } from './infra/logger.js'
export { OllamaClient } from './llm/ollama.js'
export { OpenAIClient } from './llm/openai.js'
export { AnthropicClient } from './llm/anthropic.js'
export { createLLMClient } from './llm/factory.js'
export { stripThink, parseModelRef } from './llm/client.js'
export type { LLMClient, LLMMessage, LLMToolDefinition, LLMResponse } from './llm/client.js'
export { ToolRegistry } from './tools/registry.js'
export type { Tool, ToolContext } from './tools/registry.js'
export { MemoryManager, extractFacts } from './memory/manager.js'
export { EventBus } from './automation/event-bus.js'
export { SchedulerEngine } from './scheduler/engine.js'
export { AgentRouter } from './agents/router.js'
export { resolveAgentRoute, makeSessionKey } from './routing/resolve-route.js'
export type { ResolvedAgentRoute } from './routing/resolve-route.js'
